/* Tests for the in-Worker heuristic text detector (Path 1).
   Verifies: signal calculations, score combination, confidence,
   and tier-correctness on known-AI vs known-human samples.
*/
'use strict';

const assert = require('node:assert/strict');
const { textHeuristic, detectText, WEIGHTS } = require('../api/ai-filter/backends/text-heuristic.js');

let passed = 0, failed = 0;
async function test(name, fn) {
  try { await fn(); console.log('  ✓ ' + name); passed++; }
  catch (e) { console.log('  ✗ ' + name + '\n    ' + e.message); failed++; }
}
const group = async (name, fn) => { console.log('\n# ' + name); await fn(); };

(async () => {

await group('Weights sum to 1.0', async () => {
  await test('sanity', () => {
    const sum = Object.values(WEIGHTS).reduce((a, b) => a + b, 0);
    assert.ok(Math.abs(sum - 1.0) < 1e-9, `weights sum to ${sum}`);
  });
});

await group('Boundary behavior', async () => {
  await test('Empty text → score 0', () => {
    const r = detectText('');
    assert.equal(r.score, 0);
  });
  await test('Very short text → score 0 (no signals fire)', () => {
    const r = detectText('Hello world.');
    assert.equal(r.score, 0);
  });
  await test('Whitespace-only → score 0', () => {
    const r = detectText('   \n\n  ');
    assert.equal(r.score, 0);
  });
});

await group('Individual signals (via composite)', async () => {
  await test('Heavy LLM tells → llmTells fires', () => {
    const text = 'It\'s important to note that we delve into the multifaceted landscape. ' +
                 'Let\'s explore this profound paradigm. In conclusion, the realm is intricate.';
    const r = detectText(text);
    assert.ok(r.signals.llmTells > 0.5, `expected llmTells>0.5, got ${r.signals.llmTells}`);
  });
  await test('Em-dash flood → emDash fires', () => {
    // 6 em-dashes in ~12 words → 500/1k words → maxes out
    const text = 'This — that — those — these — there — they — them. A short sentence here for length. And another one for good measure.';
    const r = detectText(text);
    assert.ok(r.signals.emDash > 0.5, `expected emDash>0.5, got ${r.signals.emDash}`);
  });
  await test('Conclusion markers fire', () => {
    const text = 'A sentence. Another. In conclusion, this proves the point. To summarize, we have demonstrated. Yet another sentence for length. And another.';
    const r = detectText(text);
    assert.equal(r.signals.conclusion, 1.0);
  });
  await test('Numbered list → parallelism fires', () => {
    const text = `Here are the items:
1. First item
2. Second item
3. Third item
4. Fourth item
5. Fifth item`;
    const r = detectText(text);
    assert.ok(r.signals.parallelism > 0.5);
  });
});

await group('Tier-correctness on real samples', async () => {
  await test('Obviously-AI boilerplate → score > 50 (BLOCK)', () => {
    const text = `In today's digital age, it's important to note that artificial intelligence has become an integral part of our lives. Let's delve into the multifaceted landscape of modern AI and explore how it can foster innovation across various industries.

The realm of machine learning is vast and intricate — a tapestry woven from decades of research. It's worth noting that practitioners must navigate this landscape with care. Moreover, they should leverage the power of these tools to harness their full potential.

Here are some key considerations:

1. Robust frameworks are essential for comprehensive deployment
2. It's crucial to embrace a holistic approach
3. Furthermore, organizations should foster a culture of continuous learning

In conclusion, the journey of integrating AI is both profound and pivotal.`;
    const r = detectText(text);
    assert.ok(r.score > 50, `expected score>50 (BLOCK), got ${r.score}`);
  });

  await test('Medium "Written by AI" article → score >= 15 (at least WARN_LOW, ideally WARN_HIGH)', () => {
    const text = `This is an Article Written by AI. This article was written by an artificial intelligence. I know that might seem odd, but take a deep breath and bear with me. There are a lot of misconceptions about artificial intelligence out there.

Here are the facts:

1. Nobody is in control of this article. I am just an algorithm that has been developed to write blog posts.
2. Artificial intelligence can be used to make humans more efficient, not replace them altogether.

Sure, some of the ideas are mine, but the words and content are significantly generated by artificial intelligence. This is groundbreaking technology. The idea that you are reading an algorithm is a fascinating one in and of itself, but it is also true.`;
    const r = detectText(text);
    assert.ok(r.score >= 15, `expected score>=15, got ${r.score}`);
    // Better than the mock's 6.4%
    assert.ok(r.score > 10, `should improve on mock 6.4%`);
  });

  await test('Genuine human creative writing → score < 30 (not BLOCK)', () => {
    const text = `The cat threw up on the kitchen floor again this morning, just as I was about to leave for work. I'd forgotten to feed her dinner last night, which was the obvious reason — she'd eaten too fast when I finally remembered around 6 a.m. Bile and a half-digested pile of kibble, right in front of the coffee maker.

My partner texted me on the train to tell me she'd cleaned it up. I felt guilty for about ten minutes, then forgot about it until lunch.

Anyway. I started this draft three weeks ago and keep coming back to it without really making progress. The problem isn't that I don't know what I want to say. It's that I don't know who I'm saying it to.`;
    const r = detectText(text);
    assert.ok(r.score < 30, `expected score<30 (not BLOCK), got ${r.score}`);
  });
});

await group('Confidence behavior', async () => {
  await test('Short text → low confidence', () => {
    const r = detectText('A short text fragment.');
    assert.ok(r.confidence <= 0.5, `expected low confidence, got ${r.confidence}`);
  });
  await test('Long text + agreeing signals → higher confidence', () => {
    const text = ('In conclusion, it\'s important to note the comprehensive landscape — moreover, the profound paradigm. ').repeat(15);
    const r = detectText(text);
    assert.ok(r.confidence >= 0.5);
  });
});

await group('Detector interface', async () => {
  await test('textHeuristic.detect() returns expected shape', async () => {
    const r = await textHeuristic.detect('Sample text for the detector.');
    assert.equal(typeof r.score, 'number');
    assert.equal(typeof r.confidence, 'number');
    assert.equal(r.backend, 'text-heuristic');
    assert.ok(r.raw && r.raw.signals);
  });
  await test('Name + modality set correctly', () => {
    assert.equal(textHeuristic.name, 'text-heuristic');
    assert.equal(textHeuristic.modality, 'text');
  });
});

await group('Determinism', async () => {
  await test('Same input → same score', () => {
    const text = 'The same text produces the same score every time.';
    const r1 = detectText(text);
    const r2 = detectText(text);
    assert.equal(r1.score, r2.score);
    assert.deepEqual(r1.signals, r2.signals);
  });
});

console.log(`\n${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
})();
